version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb
    restart: always
    ports:
      - "27017:27017"
    logging:
      driver: "none"

volumes:
  MONGO_DATA:
    name: MONGO_DATA
  MONGO_CONFIG:
    name: MONGO_CONFIG
